import type { Digest, TaskId } from "../domain/ids.js";
import type { ProviderAccessMode, ProviderAuthMode, ProviderBillingMode, ProviderTransport } from "./provider-contract.js";
import type { ProviderReportedUsage } from "./provider-usage.js";

export type ProviderExecutionReceipt = {
  executionId?: string;
  taskId: TaskId;
  tenantId: string;
  requestFp: Digest;
  workOrderFp?: Digest;
  capability: string;
  providerId: string;
  providerAdapterVersionFp?: Digest;
  accessMode: ProviderAccessMode;
  transport?: ProviderTransport;
  authMode?: ProviderAuthMode;
  billingPath?: ProviderBillingMode;
  seatId?: string;
  routingPolicyFp?: Digest;
  inputFp: Digest;
  outputFp?: Digest;
  workspaceBeforeFp?: Digest;
  workspaceAfterFp?: Digest;
  startedAt: string;
  completedAt: string;
  result: "SUCCESS" | "FAIL" | "TIMEOUT" | "BLOCKED";
  failureCode?: string;
  failoverFrom?: string[];
  usage?: ProviderReportedUsage;
  costReceiptFp?: Digest;
  receiptFp: Digest;
};
